name: dacsslide
version: 0.0.2
author: Valentyn Shybanov <olostan@gmail.com>
description: Dart CSS presentation framework.
homepage: https://github.com/olostan/dacsslide
dependencies:
  angular: '>=0.9.7 <1.0.0'
  browser: '>=0.9.1 <1.0.0'

transformers:
- angular:
    html_files:
    - lib/presentation.html